const $=id=>document.getElementById(id),S={world:{name:"No world loaded",dimension:"—",version:null,spawn:null},chunks:[],players:[],pois:[],regions:new Map(),sel:null,zoom:1,panX:0,panY:0,drag:null};
const C=$("map"),X=C.getContext("2d"),filesByPath=f=>f.webkitRelativePath||f.name,base=p=>p.split("/").pop(),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
class R{constructor(b){this.d=new DataView(b);this.o=0}need(n){if(this.o+n>this.d.byteLength)throw Error("Truncated NBT")}u8(){this.need(1);return this.d.getUint8(this.o++)}i8(){this.need(1);return this.d.getInt8(this.o++)}i16(){this.need(2);let v=this.d.getInt16(this.o);this.o+=2;return v}i32(){this.need(4);let v=this.d.getInt32(this.o);this.o+=4;return v}i64(){this.need(8);let v=this.d.getBigInt64(this.o);this.o+=8;return v}f32(){this.need(4);let v=this.d.getFloat32(this.o);this.o+=4;return v}f64(){this.need(8);let v=this.d.getFloat64(this.o);this.o+=8}bytes(n){this.need(n);let v=new Uint8Array(this.d.buffer,this.d.byteOffset+this.o,n);this.o+=n;return v}str(){let n=this.d.getUint16(this.o);this.o+=2;return new TextDecoder().decode(this.bytes(n))}}
const TN={1:"byte",2:"short",3:"int",4:"long",5:"float",6:"double",7:"byte[]",8:"string",9:"list",10:"compound",11:"int[]",12:"long[]"};
function tag(r,t,n="",d=0){if(d>60)throw Error("NBT too deep");if(t===0)return{t,n,v:null};if(t===1)return{t,n,v:r.i8()};if(t===2)return{t,n,v:r.i16()};if(t===3)return{t,n,v:r.i32()};if(t===4)return{t,n,v:r.i64()};if(t===5)return{t,n,v:r.f32()};if(t===6)return{t,n,v:r.f64()};if(t===7){let n2=Math.max(0,r.i32());return{t,n,v:[...r.bytes(n2)]}}if(t===8)return{t,n,v:r.str()};if(t===9){let it=r.u8(),n2=Math.max(0,r.i32()),a=[];for(let i=0;i<n2;i++)a.push(tag(r,it,"",d+1));return{t,n,v:{it,a}}}if(t===10){let o={};for(;;){let ct=r.u8();if(ct===0)break;let cn=r.str();o[cn]=tag(r,ct,cn,d+1)}return{t,n,v:o}}if(t===11){let n2=Math.max(0,r.i32()),a=[];for(let i=0;i<n2;i++)a.push(r.i32());return{t,n,v:a}}if(t===12){let n2=Math.max(0,r.i32()),a=[];for(let i=0;i<n2;i++)a.push(r.i64());return{t,n,v:a}}throw Error("Unknown NBT tag "+t)}
function nbt(b){let r=new R(b),t=r.u8();if(!t)return{t:0,n:"",v:null};return tag(r,t,r.str())}
const root=n=>n?.t===10?n.v:{}, get=(n,k,d=null)=>root(n)[k]?.v??d;
async function ungzip(b){return new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer()}
async function unzlib(b){return new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream("deflate"))).arrayBuffer()}
async function decode(b,c){return c===1?ungzip(b):c===2?unzlib(b):Promise.reject(Error("Unsupported compression "+c))}
async function readDat(f){let b=new Uint8Array(await f.arrayBuffer());if(b[0]===31&&b[1]===139)b=new Uint8Array(await ungzip(b));else try{b=new Uint8Array(await unzlib(b))}catch{}return nbt(b)}
function num(n,d=null){let v=n?.v;return typeof v==="bigint"?Number(v):typeof v==="number"?v:d}
function plain(n,d=0){if(!n||d>35)return"[depth limit]";if(n.t===4)return n.v.toString();if(n.t===9)return n.v.a.map(x=>plain(x,d+1));if(n.t===10)return Object.fromEntries(Object.entries(n.v).map(([k,v])=>[k,plain(v,d+1)]));return n.v}
function posFromLong(v){let u=BigInt.asUintN(64,v),sg=(x,b)=>x&(1<<(b-1))?x-(1<<b):x;return{x:sg(Number((u>>38n)&0x3ffffffn),26),y:sg(Number((u>>26n)&0xfffn),12),z:sg(Number(u&0x3ffffffn),26)}}
function decodeRegion(f){return f.arrayBuffer().then(async b=>{let d=new DataView(b),m=filesByPath(f).match(/r\.(-?\d+)\.(-?\d+)\.mca$/i),rx=+(m?.[1]||0),rz=+(m?.[2]||0),out=[];for(let i=0;i<1024;i++){let off=d.getUintBE(i*4),sec=d.getUint8(i*4+3);if(!off||!sec)continue;let at=off*4096;if(at+5>d.byteLength)continue;let len=d.getUint32(at),cmp=d.getUint8(at+4);if(len<2||at+5+len-1>d.byteLength)continue;try{let raw=await decode(new Uint8Array(b,at+5,len-1),cmp),z=nbt(raw),q=root(z).Level?.v||root(z),x=num(q.xPos,rx*32+(i&31)),zz=num(q.zPos,rz*32+(i>>5)),hm=q.Heightmaps?.v?.WORLD_SURFACE||q.Heightmaps?.v?.MOTION_BLOCKING;out.push({x,z:zz,rx,rz,nbt:z,status:String(q.Status?.v||"unknown"),height:hm?.v||null,size:sec*4096})}catch(e){out.push({x:rx*32+(i&31),z:rz*32+(i>>5),rx,rz,status:"Unreadable",nbt:null})}}return out})}
function worldName(fs){let f=fs.find(x=>base(filesByPath(x)).toLowerCase()==="level.dat");if(!f)return"Minecraft World";let p=filesByPath(f).split("/");return p.length>1?p[p.length-2]:"Minecraft World"}
async function load(fs){S.world={name:worldName(fs),dimension:"overworld",version:null,spawn:null};S.chunks=[];S.players=[];S.pois=[];S.regions.clear();let norm=fs.map(f=>({f,p:filesByPath(f),l:filesByPath(f).toLowerCase()})),lev=norm.find(x=>base(x.l)==="level.dat");if(lev)try{let n=await readDat(lev.f),d=root(n).Data?.v||root(n);S.world.version=num(d.DataVersion);let x=num(d.SpawnX),y=num(d.SpawnY),z=num(d.SpawnZ);if([x,y,z].every(Number.isFinite))S.world.spawn={x,y,z};S.world.dimension=String(d.Dimension?.v||"overworld")}catch{}
let regs=norm.filter(x=>/^(?:.*\/)?region\/r\.-?\d+\.-?\d+\.mca$/i.test(x.p)), pfs=norm.filter(x=>/^(?:.*\/)?playerdata\/[^/]+\.dat$/i.test(x.p)), pois=norm.filter(x=>/^(?:.*\/)?poi\/r\.-?\d+\.-?\d+\.mca$/i.test(x.p));
for(let f of regs){let cs=await decodeRegion(f.f);S.chunks.push(...cs);if(cs[0])S.regions.set(f.p,{x:cs[0].rx,z:cs[0].rz,n:cs.length})}
for(let f of pfs)try{let n=await readDat(f.f),r=root(n),pn=r.Pos?.v?.a?.map(x=>Number(x.v)),uuid=base(f.p).replace(/\.dat$/i,"");S.players.push({name:uuid,uuid,pos:pn?.length===3?{x:pn[0],y:pn[1],z:pn[2]}:null,dimension:String(r.Dimension?.v||"?"),health:num(r.Health),nbt:n})}catch{}
for(let f of pois){let cs=await decodeRegion(f.f);for(let c of cs){let q=root(c.nbt),sections=q.Sections||q.sections;if(sections?.v)for(let s of Object.values(sections.v))for(let rec of (s.v?.records?.v?.a||s.v?.a||[])){let pn=rec.v?.pos?.v;if(rec.v?.type?.v&&typeof pn==="bigint"){let p=posFromLong(pn);S.pois.push({type:String(rec.v.type.v),...p,nbt:rec})}}}}
$("worldName").textContent=S.world.name;$("dimension").textContent=S.world.dimension;$("version").textContent=S.world.version??"—";$("spawn").textContent=S.world.spawn?Object.values(S.world.spawn).join(", "):"—";$("chunks").textContent=S.chunks.length.toLocaleString();$("regions").textContent=S.regions.size.toLocaleString();$("players").textContent=S.players.length.toLocaleString();$("pois").textContent=S.pois.length.toLocaleString();$("regionSize").textContent=S.regions.size;$("mapTitle").textContent=S.world.name; $("empty").classList.add("hidden"); renderLists();fit();draw()}
function renderLists(){let q=$("playerSearch").value.toLowerCase();$("playerList").innerHTML=S.players.filter(p=>p.name.toLowerCase().includes(q)).map((p,i)=>`<button class="item" data-p="${i}"><span class="icon">♙</span><span class="copy"><span class="name">${esc(p.name)}</span><span class="small">${p.pos?Math.round(p.pos.x)+", "+Math.round(p.pos.y)+", "+Math.round(p.pos.z):"no position"}</span></span></button>`).join("")||"No players loaded.";q=$("poiSearch").value.toLowerCase();$("poiList").innerHTML=S.pois.filter(p=>(p.type+" "+p.x+" "+p.y+" "+p.z).toLowerCase().includes(q)).slice(0,300).map((p,i)=>`<button class="item" data-o="${i}"><span class="icon">⌁</span><span class="copy"><span class="name">${esc(p.type)}</span><span class="small">${p.x}, ${p.y}, ${p.z}</span></span></button>`).join("")||"No POIs loaded.";$("regionList").innerHTML=[...S.regions.values()].map(r=>`<button class="item" data-r="${r.x},${r.z}"><span class="icon">▦</span><span class="copy"><span class="name">r.${r.x}.${r.z}.mca</span><span class="small">${r.n} active chunks</span></span></button>`).join("")||"No regions loaded."}
function center(){if(!S.chunks.length)return{x:0,z:0};let xs=S.chunks.map(c=>c.x),zs=S.chunks.map(c=>c.z);return{x:(Math.min(...xs)+Math.max(...xs))/2,z:(Math.min(...zs)+Math.max(...zs))/2}}
function fit(){let r=C.getBoundingClientRect(),c=center(),xs=S.chunks.map(x=>x.x),zs=S.chunks.map(x=>x.z);S.zoom=xs.length?Math.max(.03,Math.min(3,r.width/(Math.max(4,Math.max(...xs)-Math.min(...xs)+1)*16*1.2),r.height/(Math.max(4,Math.max(...zs)-Math.min(...zs)+1)*16*1.2))):1;S.panX=0;S.panY=0}
function scr(wx,wz){let r=C.getBoundingClientRect(),c=center();return{x:r.width/2+(wx-c.x*16)*S.zoom+S.panX,y:r.height/2+(wz-c.z*16)*S.zoom+S.panY}}
function world(x,y){let r=C.getBoundingClientRect(),c=center();return{x:(x-r.width/2-S.panX)/S.zoom+c.x*16,z:(y-r.height/2-S.panY)/S.zoom+c.z*16}}
function draw(){let r=C.getBoundingClientRect();X.clearRect(0,0,r.width,r.height);X.fillStyle="#0b131c";X.fillRect(0,0,r.width,r.height);for(let c of S.chunks){let p=scr(c.x*16,c.z*16),h=c.height?c.height.reduce((a,b)=>a+b,0)/256:80,t=Math.max(0,Math.min(1,(h+64)/448)),g=Math.floor(55+t*100);X.fillStyle=`rgb(${35+g/3},${55+g/2},${55+t*35})`;X.fillRect(p.x,p.y,16*S.zoom+.4,16*S.zoom+.4)}for(let p of S.players)if(p.pos){let q=scr(p.pos.x,p.pos.z);X.fillStyle="#6ea8ff";X.beginPath();X.arc(q.x,q.y,4,0,7);X.fill()}for(let p of S.pois){let q=scr(p.x,p.z);X.fillStyle="#f8c86b";X.fillRect(q.x-2,q.y-2,4,4)}if(S.sel?.x!==undefined){let q=scr(S.sel.x*16,S.sel.z*16);X.strokeStyle="#4ce0a1";X.lineWidth=3;X.strokeRect(q.x,q.y,16*S.zoom,16*S.zoom)}}
function inspect(title,meta,n){$("detailTitle").textContent=title;$("detailMeta").textContent=meta||"";$("export").disabled=!n;S.selNbt=n;$("detail").innerHTML=n?renderNode(n):""}
function renderNode(n){let out=`<div class="inspector"><div class="inspecthead">${esc(TN[n.t]||"NBT")}</div><div class="node">`;if(n.t===10){for(let v of Object.values(n.v).slice(0,500))out+=renderNode(v)}else if(n.t===9){for(let [i,v] of n.v.a.slice(0,500).entries()){v={...v,n:String(i)};out+=renderNode(v)}}else out+=`<div class="nrow"><span class="nname">${esc(n.n||"value")}</span><span class="ntype">${TN[n.t]}</span><span class="nval">${esc(Array.isArray(n.v)?`[${n.v.length} values]`:typeof n.v==="bigint"?n.v.toString():n.v)}</span></div>`;return out+"</div></div>"}
function select(n){S.sel=n;draw()}
$("world").onchange=e=>load([...e.target.files]);$("files").onchange=e=>load([...e.target.files]);$("playerSearch").oninput=renderLists;$("poiSearch").oninput=renderLists;$("playerList").onclick=e=>{let b=e.target.closest("[data-p]");if(!b)return;let p=S.players[+b.dataset.p];S.sel={x:p.pos?.x/16||0,z:p.pos?.z/16||0};inspect(p.name,`${p.dimension} · ${p.pos?Object.values(p.pos).map(Math.round).join(", "):"no position"}`,p.nbt);draw()};$("poiList").onclick=e=>{let b=e.target.closest("[data-o]");if(!b)return;let p=S.pois[+b.dataset.o];S.sel={x:p.x/16,z:p.z/16};inspect(p.type,`${p.x}, ${p.y}, ${p.z}`,p.nbt);draw()};$("regionList").onclick=e=>{let b=e.target.closest("[data-r]");if(!b)return;let [x,z]=b.dataset.r.split(",").map(Number),c=S.chunks.find(c=>c.rx===x&&c.rz===z);if(c)inspect(`Region ${x}, ${z}`,`${c.nbt?"NBT available":"no NBT"}`,c.nbt)};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.pane").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.pane).classList.add("active")});
$("export").onclick=()=>{let b=new Blob([JSON.stringify(plain(S.selNbt),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="minecraft-inspection.json";a.click()};
$("plus").onclick=()=>{S.zoom=Math.min(6,S.zoom*1.25);draw()};$("minus").onclick=()=>{S.zoom=Math.max(.03,S.zoom/1.25);draw()};$("reset").onclick=()=>{fit();draw()};C.onwheel=e=>{e.preventDefault();S.zoom=Math.max(.03,Math.min(6,S.zoom*(e.deltaY<0?1.15:.87)));draw()};C.onpointerdown=e=>{S.drag={x:e.clientX,y:e.clientY,px:S.panX,py:S.panY};C.classList.add("drag")};C.onpointermove=e=>{let r=C.getBoundingClientRect(),w=world(e.clientX-r.left,e.clientY-r.top);$("coords").textContent=`Chunk ${Math.floor(w.x/16)}, ${Math.floor(w.z/16)} · Block ${Math.floor(w.x)}, ${Math.floor(w.z)}`;if(S.drag){S.panX=S.drag.px+e.clientX-S.drag.x;S.panY=S.drag.py+e.clientY-S.drag.y;draw()}};C.onpointerup=()=>{S.drag=null;C.classList.remove("drag")};addEventListener("resize",()=>{fit();draw()});document.ondragover=e=>{e.preventDefault();$("drop").classList.remove("hidden")};document.ondragleave=e=>{if(e.clientX<2||e.clientY<2||e.clientX>innerWidth-2||e.clientY>innerHeight-2)$("drop").classList.add("hidden")};document.ondrop=e=>{e.preventDefault();$("drop").classList.add("hidden");load([...e.dataTransfer.files])};fit();draw();